/*
 * This source file was generated by the Gradle 'init' task
 */
package org.ticketBooking;

import org.ticketBooking.repository.UserRepository;
import org.ticketBooking.services.UserService;

public class App {

    public static void main(String[] args){
        UserRepository userRepository = new UserRepository();
        UserService userService = new UserService(userRepository);

        userService.printUser();
        userService.signup("user.one", "user.one@gmail.com", "12345678");
        userService.printUser();
    }
}
