/*
 * This source file was generated by the Gradle 'init' task
 */
package org.ticketBooking;

import org.ticketBooking.services.SystemServices;

public class App {

    public static void main(String[] args){
        SystemServices systemServices = new SystemServices();
        boolean isInterrupted = false;
        while(!isInterrupted){
            systemServices.printMenu();
            isInterrupted = systemServices.serve();
        }
        System.out.println("\nTHANKS\n");
    }
}
